default:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
  rhino_log_file: !expr Sys.getenv("RHINO_LOG_FILE", NA)

organ_tab:
  tab_items:
    - name: "Brain"
      tab_url: "brain"
      icon: "brain.png"
    - name: "Heart"
      tab_url: "heart"
      icon: "heart.png"
    - name: "Blood"
      tab_url: "blood"
      icon: "blood.png"

