name: Azure Container Registry

on:
  push:
    # branches:
    #   # - main
  workflow_dispatch:

env:
  IMAGE_NAME: caffein-app

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'caffeine'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_0a8e9adba48344a889fbafaf4a73377f }}
          images: 'esqlabs.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b28885d08d84434c8cde8870bd9d6513 }}/caffein-app:${{ github.sha }}'
